version: '3'

networks:
  database:
    internal: true
  api:
    internal: true
  proxy:

services:
  mysql-cashflow-api:
    image: mysql:8.0
    container_name: mysql-poi-api
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'poi'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - database

  app-poi-api:
    build:
      context: ./app/
      dockerfile: Dockerfile
    image: app-poi-api
    container_name: app-poi-api
    restart: unless-stopped
    networks:
      - api
      - database
    depends_on:
      - mysql-poi-api
    ports:
      - 8080:8080  # Adicione esta linha para mapear a porta 8080

  proxy-cashflow-api:
    image: nginx
    container_name: proxy-poi-api
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf
    ports:
      - 80:80
    networks:
      - proxy
      - api
    depends_on:
      - app-poi-api
