version: '3'

services:
  mysql-poi-api:
    image: mysql:8.0
    container_name: mysql-poi-api
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'poi'
      MYSQL_USER: 'poi_user'
      MYSQL_PASSWORD: 'poi123'
      MYSQL_ROOT_HOST: '%'
      MYSQL_AUTH_PLUGIN: 'caching_sha2_password'
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - database
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 5

  app-poi-api:
    build:
      context: .
      dockerfile: /Dockerfile
    image: app-poi-api
    container_name: app-poi-api
    restart: unless-stopped
    networks:
      - api
      - database
    depends_on:
      - mysql-poi-api
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  database:
    internal: true
  api:
    driver: bridge