version: '3.8'

services:

  database:
    image: postgres
    container_name: database-api-poi
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - APP_DB_USER=poiuser
      - APP_DB_PASS=poipsw
      - APP_DB_NAME=poi
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/db/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh
      - ./postgres/data:/var/lib/postgresql/data